site/website/models.py
from datetime import datetime, timedelta, timezone
from flask_login import UserMixin
from . import db

class ModeloDeTarefa(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(50))
    descricao = db.Column(db.Text)
    pontos = db.Column(db.Integer)

class Tarefa(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    usuario_id = db.Column(db.Integer, db.ForeignKey('usuario.id'))
    modelo_id = db.Column(db.Integer, db.ForeignKey('modelo_de_tarefa.id'))

    data_criacao = db.Column(db.DateTime, default=datetime.now(timezone.utc))
    data_expiracao = db.Column(db.DateTime, default=datetime.now(timezone.utc) + timedelta(days=7))

    status = db.Column(db.String(20), default='pendente')
    
    usuario = db.relationship('Usuario', back_populates='tarefas')
    modelo = db.relationship('ModeloDeTarefa')

class Usuario(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(30))
    email = db.Column(db.String(50), unique=True)
    senha = db.Column(db.String(50))
    
    admin = db.Column(db.Boolean, default=False)

    pontos = db.Column(db.Integer, default=0)

    tarefas = db.relationship('Tarefa', back_populates='usuario')

site/website/__init__.py
import os
from datetime import datetime
from dotenv import load_dotenv
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
# from flask_jwt_extended import JWTManager
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.schedulers import SchedulerNotRunningError

load_dotenv()

db = SQLAlchemy()
DB_NAME = 'database.db'

scheduler = BackgroundScheduler()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

    # app.config['JWT_SECRET_KEY'] = os.getenv('JWT_SECRET_KEY')
    # app.config['JWT_ACCESS_TOKEN_EXPIRES'] = False
    # jwt = JWTManager(app)

    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .products import products
    from .admin import admin
    from .api import api
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(products, url_prefix='/products')
    app.register_blueprint(admin, url_prefix='/admin')
    app.register_blueprint(api, url_prefix='/api')

    from .models import Usuario

    criar_database(app)
    iniciar_scheduler(app)

    login_manager = LoginManager()
    login_manager.session_protection = 'basic'
    login_manager.login_view = 'auth.login'
    login_manager.login_message = ''
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Usuario.query.get(int(id))
    
    return app

def criar_database(app):
    if not os.path.exists(os.path.join(app.instance_path, DB_NAME)):
        with app.app_context():
            db.create_all()
        print('Banco de dados criado!')

def iniciar_scheduler(app):
    with app.app_context():
        if not scheduler.running:
            from .tasks import atualizar_usuarios
            scheduler.add_job(func=lambda: atualizar_usuarios(app), trigger='interval', weeks=1, next_run_time=datetime.now())
            scheduler.start()

        @app.teardown_appcontext
        def shutdown_session(exception=None):
            try:
                if scheduler.running:
                    scheduler.shutdown(wait=False)
            except SchedulerNotRunningError:
                pass

site/website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.exceptions import BadRequestKeyError
from . import db
from .models import Usuario

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    if request.method == 'POST':
        email = request.form.get('email')
        senha = request.form.get('senha')
        lembrar = request.form.get('lembrar') == 'on'

        user = Usuario.query.filter_by(email=email).first()
        if user and check_password_hash(user.senha, senha):
            flash('Logado com sucesso!', category='success')
            # LEMBRAR DE MIM NÃO FUNCIONANDO, CONSERTAR DEPOIS
            login_user(user, remember=lembrar)
            return redirect(url_for('views.home'))  
        flash('Email ou senha incorreto, tente novamente!', category='error')
    
    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    if request.method == 'POST':
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha1 = request.form.get('senha1')
        senha2 = request.form.get('senha2')

        user = Usuario.query.filter_by(email=email).first()
        if user:
            flash('Email já registrado.', category='error')

        elif len(nome) < 2:
            flash('O nome precisa ter pelo menos 2 caracteres.', category='error')
        elif len(nome) > 30:
            flash('O nome não pode ter mais de 30 caracteres', category='error')

        elif len(email) < 5:
            flash('O email precisa ter pelo menos 5 caracteres.', category='error')
        elif len(email) > 50:
            flash('O email não pode ter mais de 50 caracteres.', category='error')

        elif len(senha1) < 8:
            flash('A senha precisa ter pelo menos 8 caracteres.', category='error')
        elif len(senha2) > 50:
            flash('A senha não pode ter mais de 50 caracteres.', category='error')

        elif senha1 != senha2:
            flash('As senhas não coincidem.', category='error')

        else:
            new_user = Usuario(nome=nome, email=email, senha=generate_password_hash(senha1))
            db.session.add(new_user)
            db.session.commit()
            flash('Conta criada com sucesso!', category='success')
            return redirect(url_for('auth.login'))
        
    return render_template('sign-up.html', user=current_user)

site/website/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from . import db
from .models import Tarefa
from .news import fetch_news

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    noticias = fetch_news()
    return render_template('home.html', usuario=current_user, noticias=noticias)

@views.route('/tasks')
@login_required
def tarefas():
    pendentes = Tarefa.query.filter_by(usuario_id=current_user.id, status='pendente').all()
    concluidas = Tarefa.query.filter_by(usuario_id=current_user.id, status='concluida').all()
    return render_template('tasks.html', usuario=current_user, pendentes=pendentes, concluidas=concluidas)

@views.route('/tasks/<int:tarefa_id>/')
@login_required
def concluir_tarefa(tarefa_id):
    tarefa = Tarefa.query.get(tarefa_id)
    
    if tarefa.status != 'concluida':
        tarefa.status = 'concluida'
        tarefa.usuario.pontos += tarefa.modelo.pontos
        db.session.commit()
    
    return redirect(url_for('views.tarefas'))

site/website/templates/assinatura.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles/assinatura.css">
    <link rel="stylesheet" href="../static/styles/assinatura-mediaquery.css">
    <link rel="shortcut icon" href="../static/images/favicon-dumbbell.ico" type="image/x-icon">
    <title>Assinatura | Treina Aí</title>
</head>
<body>
    <section id="container">
        <section id="assinatura">
            <div id="titulo">
                <h1>Opções de assinatura</h1>
            </div>
            <div id="content">
                <!-- <div class="tempo">
                    <span>Mensal</span>
                    <span>Semestral</span>
                    <span>Anual</span>
                </div>
                <div class="preco">
                    <span>49,99R$</span>
                    <span>152,99R$</span>
                    <span>273,99R$</span>
                </div>
                <div class="botoes">
                    <input type="submit" value="Assinar">
                    <input type="submit" value="Assinar">
                    <input type="submit" value="Assinar">
                </div> -->
                <span class="titulo">Mensal</span>
                <span class="preco">49,99R$</span>
                <input type="submit" class="botao" value="Assinar">
                
                <span class="titulo">Semestral</span>
                <span class="preco">152,99R$</span>
                <input type="submit" class="botao" value="Assinar">

                <span class="titulo">Anual</span>
                <span class="preco">273,99R$</span>
                <input type="submit" class="botao" value="Assinar">
            </div>
        </section>
    </section>
</body>
</html>

site/website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>Bem-vindo, {{ nome }}!</h1>
    <p>Você está logado com sucesso.</p>
</body>
</html>

site/website/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles/home.css">
    <link rel="stylesheet" href="../static/styles/mediaquery-home.css">
    <link rel="shortcut icon" href="../static/images/favicon-dumbbell.ico" type="image/x-icon">
    <title>Home | Treina.Aí</title>
</head>
<body>
    <header>
        <div></div>
    </header>
    <main>
        <h1>Bem-vindo, {{ usuario.nome }}!</h1>
        <section id="tarefas">
            <h2>Tarefas</h2>
            <div id="pontos">
                Pontos: {{ usuario.pontos }}
            </div>
            <ul>
                <a href="{{ url_for('views.tarefas') }}" target="_self" rel="internal">
                    <div class="listatarefa">
                        {% for tarefa in usuario.tarefas[:6] %}
                        <li>
                            {{ tarefa.modelo.titulo }}
                        </li>
                        {% endfor %}
                        <!-- <li>listitem1</li>
                        <li>listitem2</li>
                        <li>listitem3</li>
                        <li>listitem4</li>
                        <li>listitem5</li>
                        <li>listitem89</li> -->
                    </div>
                </a>
            </ul>
        </section>
        <section id="produtos">
            <h2>Produtos</h2>
            <div class="produtos-grid">
                <a href="{{ url_for('products.camisa') }}"><img src="../static/images/camisaesportiva.jpg" alt="Produto camisa"></a>
                <a href="{{ url_for('products.creatina') }}"><img src="../static/images/creatina.jpg" alt="Produto creatina"></a>
                <a href="{{ url_for('products.whey') }}"><img src="../static/images/whey.png" alt="Produto whey"></a>
                <a href="{{ url_for('products.garrafa') }}"><img src="../static/images/garrafaesportiva.png" alt="Produto garrafa"></a>
            </div>
        </section>
        <section id="noticias">
            <h2>Notícias</h2>
            {% for noticia in noticias[:10] %}
                <div class="noticia">
                    <h3><a href="{{ noticia.url }}" target="_blank">{{ noticia.title }}</a></h3>
                    <p>{{ noticia.description }}</p>
                    <small>{{ noticia.publishedAt }}</small>
                </div>
                {% if not loop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
            <!-- <div class="noticia">
                <h3><a href="#" target="_blank">Lorem, ipsum dolor sit amet consectetur adipisicing elit.</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quo autem illo totam? Voluptatum earum, sequi iste laborum fugit ipsam quo praesentium sed quod!</p>
                <small>??/??/???? ??:??</small>
                <hr>
            </div>
            <div class="noticia">
                <h3><a href="#" target="_blank">Lorem, ipsum dolor sit amet consectetur adipisicing elit.</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quo autem illo totam? Voluptatum earum, sequi iste laborum fugit ipsam quo praesentium sed quod!</p>
                <small>??/??/???? ??:??</small>
                <hr>
            </div>
            <div class="noticia">
                <h3><a href="#" target="_blank">Lorem, ipsum dolor sit amet consectetur adipisicing elit.</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quo autem illo totam? Voluptatum earum, sequi iste laborum fugit ipsam quo praesentium sed quod!</p>
                <small>??/??/???? ??:??</small>
            </div> -->
        </section>
    </main>
    <!--Terminar os conteúdos do footer--> 
    <footer id="rodape">
        <p>Treina.Aí é um projeto corporativo desenvolvido por uma equipe de desenvolvedores juvenis que atualmente não possuem espaço no mercado de trabalho, no entanto, a partir deste projeto, que tem o foco de proporcionar uma melhor qualidade de vida através de uma assinatura que disponibiliza diversos benefícios como: tarefas semanais envolvendo o tipo de treino que você precisa para alcançar suas metas de vida, pontos adquiríveis que podem ser gastos em produtos para treino ou uso comum, que se não forem comprados por meio de pontos, possuem um ótimo desconto em relação ao seu preço original no mercado. </p>
        <hr>
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>

site/website/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles/login.css"> 
    <link rel="stylesheet" href="../static/styles/mediaquery-login.css">
    <link rel="shortcut icon" href="../static/images/favicon-dumbbell.ico" type="image/x-icon">
    <title>Entrar | Treina Aí</title>
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == "error" %}
                <div class="mensagem erro">
                    {{ message }}
                    <button type="button" class="close" onclick="fecharMensagem(this)">
                        &times;
                    </button>
                </div>
            {% else %}
                <div class="mensagem sucesso">
                    {{ message }}
                    <button type="button" class="close" onclick="fecharMensagem(this)">
                        &times;
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}
    <main>
        <section id="login">
            <div id="titulo">
            </div>
            <div id="form">
                <div id="content">
                    <form method="post" autocomplete="on">
                        <div class="campo">
                            <label for="iemail">Email:</label>
                            <input name="email" type="email" id="iemail" autocomplete="email" placeholder="seuemail@gmail.com" required minlength="5" required maxlength="50">
                        </div>
                        <div class="campo">
                            <label for="isenha">Senha:</label>
                            <input name="senha" type="password" id="isenha"  placeholder="Senha" autocomplete="current-password" required minlength="8" required maxlength="50">
                        </div>
                        <div class="checkbox">
                            <input name="lembrar" type="checkbox" id="icheck">
                            <label for="icheck" style="font-size: 0.8em;">Lembrar de mim</label>
                        </div>
                        <div id="botoes">
                            <input type="submit" class="botao" value="Entrar">
                            <a href="{{ url_for('auth.sign_up') }}" class="botao">Inscreva-se</a>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>

    <!-- <script src="{{ url_for('static', filename='scripts/script.js') }}"></script> -->
    <script src="../static/scripts/script.js"></script>
</body>
</html>

site/website/templates/produtos/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título padrão{% endblock %}</title>
    <link rel="stylesheet" href="../../static/styles/produto.css">
    <link rel="stylesheet" href="../../static/styles/mediaquery-produto.css">
    <link rel="shortcut icon" href="../../static/images/favicon-dumbbell.ico" type="image/x-icon">
</head>
<body>
    <header>
        <div></div>
    </header>
    <main>
        <section id="produto">
            <div id="imagem">
                <img src="../../static/images/whey.png" alt="Whey Protein">
            </div>
            <div id="info">
                <div id="nome">
                    <h2>{% block nome %}Nome{% endblock %}</h2>
                </div>
                <div id="valor">
                    <span>{% block valor %}R$00,00{% endblock %}</span>
                    <p>{% block valor_parcelado %}em até 0x de R$00,00 sem juros{% endblock %}</p>
                </div>
                <div id="form">
                    <form action="">
                        <input type="submit" value="Comprar">
                    </form>
                </div>
                <hr>
                <div id="descricao">
                    <h3>Descrição do produto</h3>
                    <p>{% block descricao %}Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia reiciendis vitae voluptatum, quisquam, dignissimos veniam iure repellat nisi harum doloremque a dolorem ducimus, fugiat dolor ab est! Praesentium, velit officia.{% endblock %}</p>
                </div>
            </div>
        </section>
    </main>
    <footer id="rodape">
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>

site/website/templates/produtos/camisa.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camisa</title>
    <link rel="stylesheet" href="../../static/styles/produto.css">
    <link rel="stylesheet" href="../../static/styles/mediaquery-produto.css">
    <link rel="shortcut icon" href="../../static/images/favicon-dumbbell.ico" type="image/x-icon">
</head>
<body>
    <header>
        <a href="{{ url_for('views.home') }}">
            <div></div>
        </a>
    </header>
    <main>
        <section id="produto">
            <div id="imagem">
                <img src="../../static/images/camisaesportiva.jpg" alt="Whey Protein">
            </div>
            <div id="info">
                <div id="nome">
                    <h2>Camisa</h2>
                </div>
                <div id="valor">
                    <span><del style="color: red;">R$69,99</del> R$55,99</span>
                    <p>em até 3x R$18,67 sem juros</p>
                </div>
                <div id="form">
                    <form action="">
                        <input type="submit" value="Comprar">
                    </form>
                </div>
                <hr>
                <div id="descricao">
                    <h3>Descrição do produto</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, facere ipsam voluptatem officiis dicta ratione quasi quisquam labore unde fugiat ipsum veritatis explicabo libero voluptates, rerum ipsa optio accusamus soluta.</p>
                </div>
            </div>
        </section>
    </main>
    <footer id="rodape">
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>

site/website/templates/produtos/creatina.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creatina</title>
    <link rel="stylesheet" href="../../static/styles/produto.css">
    <link rel="stylesheet" href="../../static/styles/mediaquery-produto.css">
    <link rel="shortcut icon" href="../../static/images/favicon-dumbbell.ico" type="image/x-icon">
</head>
<body>
    <header>
        <a href="{{ url_for('views.home') }}">
            <div></div>
        </a>
    </header>
    <main>
        <section id="produto">
            <div id="imagem">
                <img src="../../static/images/creatina.jpg" alt="Creatina">
            </div>
            <div id="info">
                <div id="nome">
                    <h2>Creatina 300g</h2>
                </div>
                <div id="valor">
                    <span><del style="color: red;">R$62,99</del> R$50,39</span>
                    <p>em até 2x R$31,45 sem juros</p>
                </div>
                <div id="form">
                    <form action="">
                        <input type="submit" value="Comprar">
                    </form>
                </div>
                <hr>
                <div id="descricao">
                    <h3>Descrição do produto</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, facere ipsam voluptatem officiis dicta ratione quasi quisquam labore unde fugiat ipsum veritatis explicabo libero voluptates, rerum ipsa optio accusamus soluta.</p>
                </div>
            </div>
        </section>
    </main>
    <footer id="rodape">
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>

site/website/templates/produtos/garrafa.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Garrafa</title>
    <link rel="stylesheet" href="../../static/styles/produto.css">
    <link rel="stylesheet" href="../../static/styles/mediaquery-produto.css">
    <link rel="shortcut icon" href="../../static/images/favicon-dumbbell.ico" type="image/x-icon">
</head>
<body>
    <header>
        <a href="{{ url_for('views.home') }}">
            <div></div>
        </a>
    </header>
    <main>
        <section id="produto">
            <div id="imagem">
                <img src="../../static/images/garrafaesportiva.png" alt="Whey Protein">
            </div>
            <div id="info">
                <div id="nome">
                    <h2>Garrafa 800ml</h2>
                </div>
                <div id="valor">
                    <span><del style="color: red;">R$25,99</del>R$20,79</span>
                    <p>em até 2x R$10,39 sem juros</p>
                </div>
                <div id="form">
                    <form action="">
                        <input type="submit" value="Comprar">
                    </form>
                </div>
                <hr>
                <div id="descricao">
                    <h3>Descrição do produto</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, facere ipsam voluptatem officiis dicta ratione quasi quisquam labore unde fugiat ipsum veritatis explicabo libero voluptates, rerum ipsa optio accusamus soluta.</p>
                </div>
            </div>
        </section>
    </main>
    <footer id="rodape">
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>

site/website/templates/sign_up.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post">
        <!-- adicionar usuario depois -->
        <label for="iemail">Email:</label>
        <input name="email" id="iemail" type="email">
        <br>
        <label for="isenha">Senha:</label>
        <input name="senha" id="isenha" type="password">
        <br>
        <input type="submit">
    </form>
    <a href="{{ url_for('auth.login') }}">Já tenho conta</a>
</body>
</html>

site/website/templates/tasks.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles/task.css">
    <link rel="stylesheet" href="../static/styles/mediaquery-task.css">
    <link rel="shortcut icon" href="../static/images/favicon-dumbbell.ico" type="image/x-icon">
    <title>Tarefas | Treina.Aí</title>
</head>
<body>
    <header>
        <a href="{{ url_for('views.home') }}">
            <div></div>
        </a>
    </header>
    <main>
        <div class="tarefas">
            <h2>Tarefas Pendentes</h2>
            <ul>
                {% for tarefa in pendentes %}
                    <li class="pendentes">
                        <a href="{{ url_for('views.concluir_tarefa', tarefa_id=tarefa.id) }}">
                            <h3>{{ tarefa.modelo.titulo }}</h3>
                            <small>Data de expiração: {{ tarefa.data_expiracao.strftime('%d/%m %H:%M') }}</small>
                            <p>{{ tarefa.modelo.descricao }}</p>
                            <strong>{{ tarefa.modelo.pontos }} pontos</strong>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="tarefas">
            <h2>Tarefas Concluídas</h2>
            <ul>
                {% for tarefa in concluidas %}
                    <li class="concluidas">
                        <h3>{{ tarefa.modelo.titulo }}</h3>
                        <small>Concluída em: {{ tarefa.data_expiracao.strftime('%d/%m %H:%M') }}</small>
                        <p>{{ tarefa.modelo.descricao }}</p>
                        <strong>{{ tarefa.modelo.pontos }} pontos</strong>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </main>
    <footer id="rodape">
        <p>Treina.Aí é um projeto corporativo desenvolvido por uma equipe de desenvolvedores juvenis que atualmente não possuem espaço no mercado de trabalho, no entanto, a partir deste projeto, que tem o foco de proporcionar uma melhor qualidade de vida através de uma assinatura que disponibiliza diversos benefícios como: tarefas semanais envolvendo o tipo de treino que você precisa para alcançar suas metas de vida, pontos adquiríveis que podem ser gastos em produtos para treino ou uso comum, que se não forem comprados por meio de pontos, possuem um ótimo desconto em relação ao seu preço original no mercado. </p>
        <hr>
        <p>Treina.Aí &#169; 2025 - todos os direitos reservados  
            <br>
            <br>
            Treina.Aí S.A
            <br>
            CNPJ: 99.999.999/0001-51
            <br>
            Endereço: Avenida Aguaçu, 079
        </p>
        <img src="../static/images/logo4.svg" alt="logo Treina Aí">
    </footer>
</body>
</html>